//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ru() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kursovaya.Properties.Resources_ru", typeof(Resources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string AboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("AboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод анализа.
        /// </summary>
        internal static string AnalysMethodToolStripMenuItem {
            get {
                return ResourceManager.GetString("AnalysMethodToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        internal static string CancelToolStripMenuItem {
            get {
                return ResourceManager.GetString("CancelToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть вкладку.
        /// </summary>
        internal static string CloseFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("CloseFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходный код программы.
        /// </summary>
        internal static string CodeToolStripMenuItem {
            get {
                return ResourceManager.GetString("CodeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать.
        /// </summary>
        internal static string CopyToolStripMenuItem {
            get {
                return ResourceManager.GetString("CopyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        internal static string CreateToolStripMenuItem {
            get {
                return ResourceManager.GetString("CreateToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вырезать.
        /// </summary>
        internal static string CutToolStripMenuItem {
            get {
                return ResourceManager.GetString("CutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string DeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("DeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Диагностика и нейтрализация ошибок.
        /// </summary>
        internal static string DiagnosticToolStripMenuItem {
            get {
                return ResourceManager.GetString("DiagnosticToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правка.
        /// </summary>
        internal static string EditToolStripMenuItem {
            get {
                return ResourceManager.GetString("EditToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string ExitToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        internal static string FileToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("FileToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классификация грамматики.
        /// </summary>
        internal static string GrammarClassToolStripMenuItem {
            get {
                return ResourceManager.GetString("GrammarClassToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грамматика.
        /// </summary>
        internal static string GrammarToolStripMenuItem {
            get {
                return ResourceManager.GetString("GrammarToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string HelpToolStripMenuItem {
            get {
                return ResourceManager.GetString("HelpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string LanguageBtn {
            get {
                return ResourceManager.GetString("LanguageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый документ *.
        /// </summary>
        internal static string newFileName {
            get {
                return ResourceManager.GetString("newFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вызов справки.
        /// </summary>
        internal static string OpenHelpToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenHelpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        internal static string OpenToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить.
        /// </summary>
        internal static string PasteToolStripMenuItem {
            get {
                return ResourceManager.GetString("PasteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список литературы.
        /// </summary>
        internal static string ReferencesToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReferencesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторить.
        /// </summary>
        internal static string RepeatToolStripMenuItem {
            get {
                return ResourceManager.GetString("RepeatToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить как.
        /// </summary>
        internal static string SaveAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string SaveToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выделить все.
        /// </summary>
        internal static string SelectAllВсеToolStripMenuItem {
            get {
                return ResourceManager.GetString("SelectAllВсеToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пуск.
        /// </summary>
        internal static string StartToolStripMenuItem {
            get {
                return ResourceManager.GetString("StartToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Постановка задачи.
        /// </summary>
        internal static string StatementToolStripMenuItem {
            get {
                return ResourceManager.GetString("StatementToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тестовый пример.
        /// </summary>
        internal static string TestToolStripMenuItem {
            get {
                return ResourceManager.GetString("TestToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст.
        /// </summary>
        internal static string TextToolStripMenuItem {
            get {
                return ResourceManager.GetString("TextToolStripMenuItem", resourceCulture);
            }
        }
    }
}
