//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kursovaya.Properties.Resources_en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About program.
        /// </summary>
        internal static string AboutToolStripMenuItem {
            get {
                return ResourceManager.GetString("AboutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method of analysis.
        /// </summary>
        internal static string AnalysMethodToolStripMenuItem {
            get {
                return ResourceManager.GetString("AnalysMethodToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string CancelToolStripMenuItem {
            get {
                return ResourceManager.GetString("CancelToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close Tab.
        /// </summary>
        internal static string CloseFileToolStripMenuItem {
            get {
                return ResourceManager.GetString("CloseFileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program source code.
        /// </summary>
        internal static string CodeToolStripMenuItem {
            get {
                return ResourceManager.GetString("CodeToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        internal static string CopyToolStripMenuItem {
            get {
                return ResourceManager.GetString("CopyToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string CreateToolStripMenuItem {
            get {
                return ResourceManager.GetString("CreateToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cut.
        /// </summary>
        internal static string CutToolStripMenuItem {
            get {
                return ResourceManager.GetString("CutToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string DeleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("DeleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diagnostics and neutralization of errors.
        /// </summary>
        internal static string DiagnosticToolStripMenuItem {
            get {
                return ResourceManager.GetString("DiagnosticToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string EditToolStripMenuItem {
            get {
                return ResourceManager.GetString("EditToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string ExitToolStripMenuItem {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string FileToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("FileToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grammar Classification.
        /// </summary>
        internal static string GrammarClassToolStripMenuItem {
            get {
                return ResourceManager.GetString("GrammarClassToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grammar.
        /// </summary>
        internal static string GrammarToolStripMenuItem {
            get {
                return ResourceManager.GetString("GrammarToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string HelpToolStripMenuItem {
            get {
                return ResourceManager.GetString("HelpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string LanguageBtn {
            get {
                return ResourceManager.GetString("LanguageBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New File *.
        /// </summary>
        internal static string newFileName {
            get {
                return ResourceManager.GetString("newFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Help.
        /// </summary>
        internal static string OpenHelpToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenHelpToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string OpenToolStripMenuItem {
            get {
                return ResourceManager.GetString("OpenToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        internal static string PasteToolStripMenuItem {
            get {
                return ResourceManager.GetString("PasteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на References.
        /// </summary>
        internal static string ReferencesToolStripMenuItem {
            get {
                return ResourceManager.GetString("ReferencesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat.
        /// </summary>
        internal static string RepeatToolStripMenuItem {
            get {
                return ResourceManager.GetString("RepeatToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        internal static string SaveAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string SaveToolStripMenuItem {
            get {
                return ResourceManager.GetString("SaveToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select All.
        /// </summary>
        internal static string SelectAllВсеToolStripMenuItem {
            get {
                return ResourceManager.GetString("SelectAllВсеToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string StartToolStripMenuItem {
            get {
                return ResourceManager.GetString("StartToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statement.
        /// </summary>
        internal static string StatementToolStripMenuItem {
            get {
                return ResourceManager.GetString("StatementToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test case.
        /// </summary>
        internal static string TestToolStripMenuItem {
            get {
                return ResourceManager.GetString("TestToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text.
        /// </summary>
        internal static string TextToolStripMenuItem {
            get {
                return ResourceManager.GetString("TextToolStripMenuItem", resourceCulture);
            }
        }
    }
}
